# Generated by Django 2.0.4 on 2019-01-11 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190111_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post1',
            new_name='Post',
        ),
    ]
