# Generated by Django 2.0.4 on 2019-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about_cdetail_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cgpa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='online',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
